### ISSUE TITLE
Expected hostname at index

### ISSUE THREAD

**Issue by hussainsultan** [jcrist/skein#10]
On master, when I try to submit hello world example from the documentation, I get the following error.
```
(py35) hussainsultan@cluster-07d2-m:~$ skein application submit helloworld-skein.yaml
Error: Failed to submit application, exception:
Expected hostname at index 7: file://:0/home/hussainsultan/payload.txt
```

**Comment by jcrist** [comment]
Hmmm, that's odd. Can you provide the contents of the yaml, the file tree you're running in, and what version of python you're using?

**Comment by hussainsultan** [comment]
```
hussainsultan@cluster-07d2-m:~$ skein --version
skein 0.0.2+17.gd3be11a
```
(py35) hussainsultan@cluster-07d2-m:~$ python --version
Python 3.5.5 :: Anaconda, Inc.
```
File:
```(py35) hussainsultan@cluster-07d2-m:~$ find `pwd` -name helloworld-skein.yaml 
/home/hussainsultan/helloworld-skein.yaml
```
File contents:
```
>>cat helloworld-skein.yaml 
name: hello_world
queue: default

services:
  my_service:
    resources:
      vcores: 1
      memory: 128
    files:
      - file: payload.txt
    commands:
      - echo "Sleeping for 60 seconds"
      - sleep 60
      - cat payload.txt
      - echo "Stopping service"
```
