### ISSUE TITLE
Add ability to run service on the application master

### ISSUE THREAD

**Issue by jcrist** [jcrist/skein#118]
Some applications have a single coordinating process (e.g. spark's driver). It may be nice to have this process also run in the same YARN container as the application master, to minimize the number of containers required. This would mostly be useful for applications that only need a single container, or ones that have a service that should never be scaled and that also dictates the lifetime of the application.

The main issue here is determining how this should be spelled. Two ideas:

1. Extend the `Master` object with fields that make sense. Not all fields of `Service` make sense for the master node (e.g. `instances` must always be 1, `depends` must be empty, etc...)

```yaml
master:
  resources:
    memory: 1024 MiB
    vcores: 1
  files:
    script.py: /path/to/script.py
  commands:
    - python script.py
```

2. Add a `service` field to the `Master` object, and check at compose time if unsupported fields are set. This is nice as it prevents duplication of fields, but also prevents future specialization of how we handle services on the application master (there may be special things we'd want to do only for services running on the application master). It also prevents configuring things like `resources` for the application master without adding additional commands.

```yaml
master:
  service:
    resources:
      memory: 1024 MiB
      vcores: 1
    files:
      script.py: /path/to/script.py
    commands:
      - python script.py
```

Right now I'm leaning towards 2, with the addition that when a service on the master node exits, the whole application shuts down. This matches with the common usage of an application driver. I may also want to name the field `driver` instead of `service` to better indicate this.
