### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ERICPENGZ** [jcrist/skein#209]
Thank you for reporting an issue.

If your issue relates to ``dask-yarn``, please open an issue in that
repository's [issue tracker](https://github.com/dask/dask-yarn/issues) instead.

When reporting an issue, please include the following:

- **A description of the bug**

   I can't import python file . But I have put them in hadoop hdfs.

- **Steps to reproduce** 

   This is my spec.yaml file .
 name: ParameterServerForFL
queue: default

master:
  files:
    ApplicationMaster.py: ApplicationMaster.py
    m_cnn: m_cnn.py
  resources:
    vcores: 1
    memory: 512 MiB
  script: |
        python3 ApplicationMaster.py

When I run ApplicationMaster.py. I got ModuleNotFoundError problem.  It 'cant import m_cnn 

- **Relevant logs/tracebacks**

    If an error occurred, please include the **full** traceback and code that
    produced it. In the case of an application failure, please also include the
    application logs. These can be retrieved via 

    ```
    $ yarn logs -applicationId <APPLICATION ID>
    ```

    You may want to glance through the logs to ensure things have been
    anonymized where appropriate.

- **Version information**

    Please include version information for the following:

    - Python version
    - Hadoop version, and distribution (e.g. CDH) if applicable
    - Skein version

**Comment by jcrist** [comment]
You're missing the `.py` suffix on `m_cnn` in the list of files. Try:

```yaml
name: ParameterServerForFL
queue: default
master:
  files:
    ApplicationMaster.py: ApplicationMaster.py
    m_cnn.py: m_cnn.py
  resources:
    vcores: 1
    memory: 512 MiB
  script: |
    python3 ApplicationMaster.py
```
