### ISSUE TITLE
docs: example doesnt work

### ISSUE THREAD

**Issue by xhudik** [jcrist/skein#225]
a possible bug in documentation:

https://github.com/jcrist/skein/blob/master/docs/source/quickstart.rst contains yaml: 
```
name: hello_world
queue: default

master:
   resources:
       vcores: 1
       memory: 512 MiB
   script: |
  	   sleep 60
       echo "Hello World!"
```
and you should run it as: `skein application submit hello_world.yaml`; however it gives:
```
Error: In file 'hello_world.yaml', Unknown extra keys for Master:
- resources
- script
```
