### ISSUE TITLE
Access Control for WebUI

### ISSUE THREAD

**Issue by jcrist** [jcrist/skein#74]
In YARN, application WebUI's are world viewable unless handled by the application (YARN handles authentication, but not authorization). Spark handles this by defaulting to world viewable, but provides the option for an access control list. We should maybe do the same.

A few questions:
- Should the access control list be by page, or just access/no-access?
- How should this look in the specification?

The simplest thing I can think of is an access/no-access acl, with a spec like:

```yaml
ui:
  acl:
    - username1
    - username2
```

**Comment by jcrist** [comment]
Ok, I'm looking at adding this in the next few days. YARN itself has 2 application-level acls - `view` and `modify`. Each of these can filter access on users and groups. Neither prevents access to the application web ui, so skein will have to manage this internally. Since mapping users to groups is very much cluster specific, and afaict yarn/hadoop doesn't provide a generic way for applications to handle this, I plan to make the ui acls handle only users for now.

The proposed spec will look like:

```yaml
acls:
  view:
    users:
      - username1
    groups:
      - group1

  modify:
    users:
      - username2

  ui:
    users:
      - username2
    # No groups field allowed for ui acls for now
```

The first two just forward the acls to YARN in the proper format, defaults are the same as YARN's. The third will be handled by an authorization filter on the web ui, default is all users (same as YARN's).
